import { test, expect, chromium } from '@playwright/test';

test('user can sign up and create an account', async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://automationexercise.com/test_cases');
  await page.getByRole('button', { name: 'Consent' }).click();
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('rex2');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('rex1231233@gmail.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.getByText('Mr.').click();
  await page.getByRole('radio', { name: 'Mr.' }).press('d');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('fvfvdbzfb');
  await page.locator('#days').selectOption('19');
  await page.locator('#months').selectOption('11');
  await page.locator('#years').selectOption('2005');
  await page.getByRole('textbox', { name: 'Last name *' }).fill('fdsvvfvxdf');
  await page.getByRole('textbox', { name: 'First name *' }).click();
  await page.getByRole('textbox', { name: 'First name *' }).fill('fvsfdvg');
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).click();
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('fvsfdvsfdv');
  await page.getByRole('textbox', { name: 'State *' }).click();
  await page.getByRole('textbox', { name: 'State *' }).fill('vgsdfvsv');
  await page.getByRole('textbox', { name: 'City * Zipcode *' }).click();
  await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('vgg');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('322534');
  await page.getByRole('textbox', { name: 'Mobile Number *' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('7847893478437');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByText('Account Created!').click();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.locator('div').filter({ hasText: 'Home  Products Cart Logout' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Home  Products Cart Logout' }).nth(2).click();
  await browser.close();
});
